import os

TELEGRAMBOTTOKEN = os.environ.get('API_BOT')
# TELEGRAMBOTTOKEN = "5812074745:AAHQOWc_ov2aUOn_JDWT-u4XKddKVajNRmM"
OPENAITOKEN = os.environ.get('API_AI')
# OPENAITOKEN = "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"
MYUSERNAME = os.environ.get('BOT_TAG')
# MYUSERNAME = "ai7906_bot" 
